spring:
  profiles:
    active:
    - dev
---
spring:
  profiles: dev 
  #开发环境
  application:
    name: microservicecloud-config-mmm-dev
---
spring:
  profiles: test
  application:
     name: microservicecloud-config-mmm-test
#编码格式一定要为utf-8